### ISSUE TITLE
White screen - kills site on install

### ISSUE THREAD

**Issue by Anonymous972** [mattkatz/Orbital-Feed-Reader#8] opened 2015-02-12 05:03 UTC
Hello,

I really like your plugin when it worked. Over on wordpress support site, which you do not read apparently, is evidence of your previous version also not able to install.

I was only able to find this support thru some stumbling around. Lets see if we get any response?

So I was running some version around 1.5. Never could get 1.9 installed. So attempted to install this new version 2 you have posted recently. on wp 4.1.

Upgrade failed to install - white screen.
Delete plugin. Tried again. fail.
Deleted plugin and tables in db, fail again.

here is the apache error log coughed up when attempting to activate the plugin.

none of the tables were created in the database. perhaps it is not dealing with custom table prefixes? I dunno. would be great if it worked.
let me know if I can help any.

[Wed Feb 11 23:46:13 2015] [error] [client xx.xx.xx.xx] WordPress database error Table 'prod_01.cu23ktu_orbital_entries' doesn't exist for query \n      ALTER TABLE cu23ktu_orbital_entries\n        DROP COLUMN updated;\n       made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), call_user_func_array, orbital_update_db_check, orbital_install_db, orbital_migrate_db, referer: http://machine.domain.com/m/wp-admin/plugins.php

[Wed Feb 11 23:46:13 2015] [error] [client  xx.xx.xx.xx] WordPress database error Table 'prod_01.cu23ktu_orbital_entries' doesn't exist for query \n      ALTER TABLE cu23ktu_orbital_entries\n        DROP COLUMN updated;\n       made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), call_user_func_array, orbital_update_db_check, orbital_install_db, orbital_migrate_db, referer: http://machine.domain.com/m/wp-admin/plugins.php

**Comment by mattkatz** [comment] 2015-02-17 18:09
I'm sorry you're having a tough time with Orbital! I really want it to be useful to you.  First, thanks for telling me instead of just abandoning it!  I'm really grateful as it gives me a chance to fix it for everyone.

I think I figured out your issue. It has to do with [these lines of code](https://github.com/mattkatz/Orbital-Feed-Reader/blob/99fa9afe4affefad8d3fe0774ec1ec11f3b20b55/install_upgrade.php#L16-L27).

Here's what I think happened. Skip to the bottom for how to fix it.
You uninstalled orbital somewhere around version 0.1.3
I've been remiss in uninstalling the DB when folks uninstall the plugin. Sometimes I think that you might want your old feeds in there if you uninstall and reinstall. Sometimes I think you'll want to start fresh. I haven't been removing tables - and maybe I should. It's been very helpful for testing, but I can see that it is causing problems for folks like you (and anyone who didn't take the trouble you did to report this issue).

When you uninstalled orbital, there's still a key in there that says what is the latest version of the orbital DB tables. I should clean that up as well, but I didn't.

Somewhere along the way, you dropped the plugin tables - but this little DB version key isn't obvious and you wouldn't have known to look for it.

When you re-install, orbital is trying to alter a table that doesn't currently exist before it does anything else. THAT's where the error you see is coming from.

#HowToFix#
In the wordpress tables, there is a table called wp_options or something like that. It will have a funny prefix like the 'cu23ktu' you see out there.

In that table will be a row with a key of 'orbital_db_version' - please delete that row.
Also delete a row with the key  'orbital_sample_data_loaded'

If any of the orbital tables still exist, drop those as well. I want to make sure you are starting clean.

That should get you to the point where you aren't getting that same error.
If #other# errors show up, I definitely would want to help you with them. If you shoot me an email with some contact info maybe I can get on a chat with you and troubleshoot it live. That way I can do the most help.  I tend to work on Orbital on Wednesday nights EST (it's one of the only times I'm not working or taking care of my kid or doing stuff with my family).  

Hope this helps - please let me know if it worked!

**Comment by Anonymous972** [comment] 2015-02-17 20:18
Hello Matt! Thanx for getting back to me.
Ok, fail again. but different. here are the results. I deleted the 2 fields in options table.
when i try to install, i get this result:
PHP Fatal error:  Cannot break/continue 1 level in /path/wp-content/plugins/orbital-feed-reader/install_upgrade.php on line 325, referer: http://machine.domain.com/m/wp-admin/plugins.php

so, then for the fun of it to see if i could get it to run up, i commented out from line: 163 in install_upgrade.php to have it not load sample data, and line 54 in orbital.php.

i did get it run up and activate. but, what i get now is an add rss feed dialog box that does nothing, will not close, will not add feeds, nothing. just sits there with the circle thingy going around and around.. cannot exit, cannot add, nothing. its pretty stuck at that point. 

ok, what do we try now?

thanx!

**Comment by mattkatz** [comment] 2015-02-18 10:42
Sounds like we're getting somewhere! I'm going to take a look now because I'm up early today. The place you're at now sounds like what I see when the angularjs library throws an error. would you mind checking if your javascript console shows any errors or log messages?

**Comment by mattkatz** [comment] 2015-02-18 10:53
Ah ha!  Currently I'd assumed that anyone running orbital would be able to edit posts. So [I only load sample data for users that can edit posts right here](https://github.com/mattkatz/Orbital-Feed-Reader/blob/master/install_upgrade.php#L323).
Unfortunately I moved code from a loop to a separate function - the continue on line 325 doesn't work outside of a loop. I should have changed that to a return.  I'll make the change on my side.

I think you'll be getting some unrelated error message in the javascript console in your browser though. Please send me what you see and I'll be happy to look into it. 

I'm really happy you're taking the time to work with me on this!

**Comment by Anonymous972** [comment] 2015-02-19 02:35
Hey Matt!

So you pretty much figured it out then.. did you make an update for me to try?
yep, heres your errors!

TypeError: string is not a function
    at new CliCtrl (controllers.js?ver=4.1.1:206)
    at invoke (angular.js?ver=4.1.1:3707)
    at Object.instantiate (angular.js?ver=4.1.1:3718)
    at $get (angular.js?ver=4.1.1:6777)
    at angular.js?ver=4.1.1:6186
    at forEach (angular.js?ver=4.1.1:310)
    at nodeLinkFn (angular.js?ver=4.1.1:6173)
    at compositeLinkFn (angular.js?ver=4.1.1:5637)
    at compositeLinkFn (angular.js?ver=4.1.1:5640)
    at publicLinkFn (angular.js?ver=4.1.1:5542)

**Comment by Anonymous972** [comment] 2015-02-19 02:42
oh btw, the install and use is on the administrator account. so, i suppose that would have edit post ability if i understood correctly..

**Comment by mattkatz** [comment] 2015-02-19 02:44
ok - the problem wasn't with the admin account - it was that there existed accounts without the edit ability.

In order to support multiple users I have to install samples for every user that could use the plugin.

I'm looking at that error and I can't see what the issue is.it isn't familiar to me just yet. I'll dig a bit.  

Any other logs? it would be great if any errors mention a line number.

**Comment by mattkatz** [comment] 2015-02-19 02:46
also, i've made some changes but haven't made a published release yet. I could push it all to a branch on github if you are familar with using that. Or I could put a zip file up on my website.

**Comment by Anonymous972** [comment] 2015-02-19 02:49
TypeError: string is not a function
    at new CliCtrl (controllers.js?ver=4.1.1:206)
    at invoke (angular.js?ver=4.1.1:3707)
    at Object.instantiate (angular.js?ver=4.1.1:3718)
    at $get (angular.js?ver=4.1.1:6777)
    at angular.js?ver=4.1.1:6186
    at forEach (angular.js?ver=4.1.1:310)
    at nodeLinkFn (angular.js?ver=4.1.1:6173)
    at compositeLinkFn (angular.js?ver=4.1.1:5637)
    at compositeLinkFn (angular.js?ver=4.1.1:5640)
    at publicLinkFn (angular.js?ver=4.1.1:5542)angular.js?ver=4.1.1:9419 (anonymous function)angular.js?ver=4.1.1:6843 $getangular.js?ver=4.1.1:12063 $get.Scope.$applyangular.js?ver=4.1.1:1302 (anonymous function)angular.js?ver=4.1.1:3707 invokeangular.js?ver=4.1.1:1300 doBootstrapangular.js?ver=4.1.1:1314 bootstrapangular.js?ver=4.1.1:1263 angularInitangular.js?ver=4.1.1:20752 (anonymous function)load-scripts.php?c=0&load[]=sack,jquery-core,jquery-migrate,utils,farbtastic,json2,underscore&ver=4…:3 m.Callbacks.jload-scripts.php?c=0&load[]=sack,jquery-core,jquery-migrate,utils,farbtastic,json2,underscore&ver=4…:3 m.Callbacks.k.fireWithload-scripts.php?c=0&load[]=sack,jquery-core,jquery-migrate,utils,farbtastic,json2,underscore&ver=4…:3 m.extend.readyload-scripts.php?c=0&load[]=sack,jquery-core,jquery-migrate,utils,farbtastic,json2,underscore&ver=4…:3 J

**Comment by Anonymous972** [comment] 2015-02-19 02:53
these errors do have a file, version and line number... 
at new CliCtrl (controllers.js?ver=4.1.1:206)
error -> file ? ver=4.1.1 :206 <-line number

**Comment by Anonymous972** [comment] 2015-02-19 02:55
When you would like to have me give it spin, you can zip it. I dont use the git, never set it up... or i can just download a zip from git..

**Comment by mattkatz** [comment] 2015-02-19 16:00
Thanks - I'm looking at that function. It's a puzzler - I haven't figured it out yet. As soon as I do, I'll put a zip file up for you to test.

Thanks!

**Comment by Anonymous972** [comment] 2015-02-22 23:29
Hi Matt! I really want to get this going again. Let me know how I can help? It occurred to me, that this info may be helpful. I was running v.1.5 when I noticed the hang in admin for the feeds. I recall now that this started after the site upgraded to 4.1. So perhaps the issue might be something in the core of how WP does things now. I know they changed a lot. ugh :(

**Comment by mattkatz** [comment] 2015-02-23 01:44
Hi @Anonymous972  - I too want to get this working. I've been sick for the past couple of days. I'll be looking at this when I have a moment or I'll dig in on it this wednesday. If you can email me anything else about your site set up that might help.   

That line number 206 should be pretty innocuous. It asks a library called 'keymaster' to set up a keyboard shortcut on the letter 'g' to bring up a search box to search your feed names. If I remove it, you lose the ability to do that. But that same library is used to go up and down through your feeds with the arrow keys or the j,k keys.

I'm still trying to figure it out.  It would be very helpful for me to get a brief time to log into your your site with a temporary account that could use orbital. I'd promise not to do anything but debug the plugin. If that makes you uncomfortable, I understand and I'll try to figure it out another way.

**Comment by Anonymous972** [comment] 2015-02-23 02:07
Hi Matt, 

I am sorry, but we are not in the usual process of allowing others into the site.
I did want to give more feedback. Using that hacked up version I got to install, as any other role then administrator, seems to work. Meaning, if the editor or author uses orbital, we do not have all the errors and are able to create and save feeds...

**Comment by mattkatz** [comment] 2015-02-23 02:20
Oh wow. Now that's very interesting. Just to make sure I understand:
Editor - orbital works fine.
Author - orbital works fine.
Administrator - orbital hangs while loading.

**Comment by Anonymous972** [comment] 2015-02-23 02:26
yes. i just tested. author, editor and contributor are all able to create, save feeds and make posts it appears without issues. but admin, has a general hang. i still see some angular error as those other users, but it functions. As administrator, it always wants to open orbital with the add feed dialog and just hangs...

**Comment by mattkatz** [comment] 2015-02-25 10:57
I'm wondering if this is due to a conflict with another plugin.

Have had a look and that's my current hypothesis. I wonder if another plugin is injecting something or doing something that somehow only shows up for an admin - but not for the other users.

The error is happening as orbital is trying to initialize a framework called Angular.JS - which is a pretty common framework. I'm wondering if you have many other plugins...

**Comment by mattkatz** [comment] 2015-02-25 10:58
Also - can you tell me what the angular issues are as those other users?

**Comment by charlietfl** [comment] 2015-08-07 14:20
Had  white screen of death across whole site on fresh install also in WP 4.1. Customer did install and I had to rename orbital plugin folder to get site live again. There were no previous instances of plugin installed

**Comment by mattkatz** [comment] 2015-08-07 21:49
Ah charlie - thank you! 
Is there any way I can contact you to ask more questions?  I want to figure this problem out and I'm trying to track it down - of **course** it doesn't happen when I install on 4.1

Thank you - let me know if there is any way to discuss with your or troubleshoot with you.

**Comment by SensicalCat** [comment] 2016-03-04 04:00
Hi Matt, are you still developing this plugin? I just tried to install and my experience is exactly the same as Anon972 above. I am trying to run up the latest version 2.1.1. I was able to follow the notes above to actually get it to install instead of killing the site. but when i got to add feeds, the dialog box does nothing. will not add sites. will not exit. will not do anything.
although I can use if I create an Editor account.
Help!
here is my console:
TypeError: key is not a function
    at new CliCtrl (controllers.js?ver=4.1.10:206)
    at invoke (angular.js?ver=4.1.10:3707)
    at Object.instantiate (angular.js?ver=4.1.10:3718)
    at angular.js?ver=4.1.10:6777
    at angular.js?ver=4.1.10:6186
    at forEach (angular.js?ver=4.1.10:310)
    at nodeLinkFn (angular.js?ver=4.1.10:6173)
    at compositeLinkFn (angular.js?ver=4.1.10:5637)
    at compositeLinkFn (angular.js?ver=4.1.10:5640)
    at publicLinkFn (angular.js?ver=4.1.10:5542)

**Comment by mattkatz** [comment] 2016-03-04 17:45
hi @SensicalCat  - I had a kid and haven't put as much time in as I used to.
I just recently started working on non-work code again.  

Currently it's set up to only work for Editors - I have a check here: https://github.com/mattkatz/Orbital-Feed-Reader/blob/master/install_upgrade.php#L323
I'll update the main page to reflect that it only works for roles that can edit posts. 

What role are you using for this?

I should also be putting in some more checking so that there is a better experience for non-editors.

The idea was that you wouldn't need orbital unless you were going to be blogging from it, so you would need to have the ability to edit a post.  

How would you see it working?

Also, feel free to send me an email with contact info and some potential times if you'd like to have a real-time chat about this. Always happy to help if I can.

**Comment by SensicalCat** [comment] 2016-03-06 11:18
Hey Matt!
Congrats on the kid!
Using an administrator. a standard account that is an administrator. Can only use orbital if user is lowered in rights. that does not seem proper. Any user with 'editor' and above should be able to use it.
So as an editor, it works. but as admin it just hangs there. Also, the sample data for the admin complete hangs the site.
maybe add option on install to 'not' install sample data. or on upgrade not to install samples.
so, ideally i would want my default user administrator account to be able to use orbital. it is a PITA to keep switching between editor account and admin account.
thanx!

**Comment by mattkatz** [comment] 2016-03-09 03:00
Ok, very strange. I'll try to create a new wordpress from scratch
Then install the plugin as the default administrator.
That should help me troubleshoot.

It is SUPPOSED to work for Editor and above, including Admin. That's how 
it is setup in my test site, so it may have something to do with going 
from a fresh install - I have been developing on the same test site for 
a while...

**Comment by SensicalCat** [comment] 2016-03-27 00:00
Hey Matt!

Touching base to see how the fixes are coming along... any news?

**Comment by mattkatz** [comment] 2016-03-30 09:26
Ok - that console log you posted earlier is very valuable.
the "Key is not a function" error means that the library I am using to handle keyboard shortcuts is either not working or not loading or some other issue. It's a bit weird that it's showing up in a stack trace that involves angular, which handles the user interface for you.  I haven't figured this out, but I can definitely look at how that gets loaded on my commute in.

I thought maybe some of this might be related to new versions of wordpress and new installs of the plugin.
So I spun up a whole new test site and installed as an Administrator, then also created Contributor and  Author user accounts.

I'm seeing an issue where the feed list shows up, but no entries get returned when I click on them. I'll troubleshoot that as well tonight and see where I get.

Thanks for hanging in there!

**Comment by mattkatz** [comment] 2016-03-30 09:48
Oh man!  Found a WHOLE nother issue - something changed in how the latest version of wordpress handle the DB stuff that orbital uses. Looks like creating this fresh install is showing tons of stuff that needs fixing - on my fresh install I'm seeing the table for entries not even get created! This has to get fixed immediately!

**Comment by mattkatz** [comment] 2016-03-30 10:27
Ok - figured out that issue. Looks like if you are using some of the new standards for DB table creating (utf8mb4) you can get an error where having a GUID (the unique identifier for a feed entry) declared as unique can throw an error. Fixed that and I can prep that for a release. 

I don't think that will catch the problem you are seeing, but I can work towards that one on my commute in.

Lucky I woke up early today!

**Comment by mattkatz** [comment] 2016-04-07 00:06
I think I have released a good fix for your issue @SensicalCat 

Please uninstall the plugin and then re-install it. It should work magically for you!

If you want to be extra helpful, you could add these two lines to your wp-config.php file *before* re-installing the plugin:

    // Enable WP_DEBUG mode
    define('WP_DEBUG', true);
    // Enable Debug logging to the /wp-content/debug.log file
    define('WP_DEBUG_LOG', true);
    // Disable display of errors and warnings 
    define('WP_DEBUG_DISPLAY', false);

Those will produce a file called debug.log in the  wp-content folder.
If it *doesn't* work, you could attach this file and it would greatly help me figure out what's happening.
If it does work, just delete those lines from the config file and you're all set!

**Comment by mattkatz** [comment] 2016-04-07 00:08
@Anonymous972 I think this fixes the issue you were getting as well! I'm going to close this issue, but please feel free to re-open if it doesn't fix for you!

Please uninstall the plugin and then re-install it. It should work magically for you!

If you want to be extra helpful, you could add these two lines to your wp-config.php file before re-installing the plugin:

// Enable WP_DEBUG mode
define('WP_DEBUG', true);
// Enable Debug logging to the /wp-content/debug.log file
define('WP_DEBUG_LOG', true);
// Disable display of errors and warnings 
define('WP_DEBUG_DISPLAY', false);

Those will produce a file called debug.log in the wp-content folder.
If it doesn't work, you could attach this file and it would greatly help me figure out what's happening.
If it does work, just delete those lines from the config file and you're all set!

**Closed by mattkatz** 2016-04-07 00:08 UTC

**Comment by SensicalCat** [comment] 2016-04-07 00:09
Sweet! I will give a run up tonight or in a day or so. let you know!
